### PR TITLE
Support Windows

### PR DESCRIPTION
**Pull request by mattn**
* gofmt
* Use daviddengcn/go-colortext instead of fatih/color for support windows
* Handle multiple arguments for toggle: `td t 2 3 4`

### CODE REVIEW

**Comment by Swatto** [comment]
I will check your fork after this weekend but could you use 2 spaces indentation for your commit please.

**Comment by mattn** [comment]
> could you use 2 spaces indentation for your commit please.

done

**Comment by Swatto** [comment]
Could you fix current conflicts with merged pull request ? I will be happy to test it on OS X to be sure that it works like it should and include it in the project.

**Comment by mattn** [comment]
Sorry I don't have enough to do it. And I already have my todo app written in go. https://github.com/mattn/todo

**Comment by mattn** [comment]
I'll make new PR in later

**Comment by Swatto** [comment]
Ok thanks for the information.

**Comment by mattn** [comment]
#15

**Pull request closed without merging**
